# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Function adding up two floats
#' @param firstOperand as first operand
#' @param secondOperand as second operand
add <- function(firstOperand, secondOperand) {
    .Call('_calculatorRcpp_add', PACKAGE = 'calculatorRcpp', firstOperand, secondOperand)
}

#' Function subtracting two floats
#' @param firstOperand as first operand
#' @param secondOperand as second operand
subtract <- function(firstOperand, secondOperand) {
    .Call('_calculatorRcpp_subtract', PACKAGE = 'calculatorRcpp', firstOperand, secondOperand)
}

#' Function multiplying two floats
#' @param firstOperand as first operand
#' @param secondOperand as second operand
multiply <- function(firstOperand, secondOperand) {
    .Call('_calculatorRcpp_multiply', PACKAGE = 'calculatorRcpp', firstOperand, secondOperand)
}

#' Function dividing two floats
#' @param firstOperand as first operand
#' @param secondOperand as second operand
divide <- function(firstOperand, secondOperand) {
    .Call('_calculatorRcpp_divide', PACKAGE = 'calculatorRcpp', firstOperand, secondOperand)
}

